### PR TITLE
Update guzzle

### PR DESCRIPTION
**Pull request by giovannipds**
Fix issue #3

### CODE REVIEW

**Comment by giovannipds** [comment]
I've also changed README file fixing the same heading errors mentioned on other PR + tried to make the readme a little more easy and comprehensible.

**Comment by giovannipds** [comment]
Feel free to contact me via [Twitter](https://twitter.com/giovannipds) so I can help in any other ways needed.

**Comment by giovannipds** [comment]
PS: I didn't run tests on it yet.

**Comment by peter279k** [comment]
The branch has conflicts and this should be solved.

**Comment by netdragoon** [comment]
New version released v2.0.1 without dependence package Guzzle 

https://github.com/netdragoon/zipcode/releases/tag/v2.0.1

**Comment by netdragoon** [comment]
Update https://github.com/netdragoon/zipcode/releases/tag/v2.0.2

**Comment by giovannipds** [comment]
Conflicts solved...

**Pull request closed without merging**
